# "Out of the box", Instiki stores it's data in sqlite3 database.
# Other options are described in the database.yml.sample_* files
# in this directory.

development:
  adapter: sqlite3
  database: db/development.db.sqlite3

test:
  adapter: sqlite3
  database: db/test.db.sqlite3

production:
  adapter: sqlite3
  database: db/production.db.sqlite3
